-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  role text default 'member' check (role in ('admin', 'member')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Create a table for events
create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  description text,
  location text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  image_url text,
  color text,
  button_text text,
  button_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on events
alter table public.events enable row level security;

-- Create policies for events
create policy "Events are viewable by everyone." on public.events
  for select using (true);

create policy "Users can insert their own events." on public.events
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own events." on public.events
  for update using (auth.uid() = user_id);

create policy "Users can delete their own events." on public.events
  for delete using (auth.uid() = user_id);

-- Admin policies (assuming we manually set a user's role to 'admin' in profiles table)
create policy "Admins can delete any event." on public.events
  for delete using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.raw_user_meta_data->>'username', 'member');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Storage Bucket Setup (You need to create a bucket named 'events' in Supabase Dashboard)
-- Policy: Public Access for reading
-- Policy: Authenticated users can upload
